version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: evaly
      MYSQL_USER: application
      MYSQL_PASSWORD: 01234



  